# Day 2 - Data Inspection

- Loaded IPL dataset
- Checked missing values
- Filtered seasons 2021–2023

In [2]:
import pandas as pd

deliveries = pd.read_csv("../data/raw/deliveries.csv")
deliveries.info()
deliveries.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 33.8 MB

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [3]:
matches = pd.read_csv("../data/raw/matches.csv")
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [4]:
matches.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

In [5]:
matches_2021_2023 = matches[
    matches["season"].isin(["2021", "2022", "2023"])
]

matches_2021_2023.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
816,1254058,2021,Chennai,2021-04-09,League,HV Patel,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,2.0,160.0,20.0,N,NaN,KN Ananthapadmanabhan,Nitin Menon
817,1254059,2021,Mumbai,2021-04-10,League,S Dhawan,"Wankhede Stadium, Mumbai",Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,wickets,7.0,189.0,20.0,N,NaN,AK Chaudhary,VK Sharma
818,1254060,2021,Chennai,2021-04-11,League,N Rana,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kolkata Knight Riders,runs,10.0,188.0,20.0,N,NaN,KN Ananthapadmanabhan,Nitin Menon
819,1254061,2021,Mumbai,2021-04-12,League,SV Samson,"Wankhede Stadium, Mumbai",Punjab Kings,Rajasthan Royals,Rajasthan Royals,field,Punjab Kings,runs,4.0,222.0,20.0,N,NaN,AK Chaudhary,S Ravi
820,1254062,2021,Chennai,2021-04-13,League,RD Chahar,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Kolkata Knight Riders,Kolkata Knight Riders,field,Mumbai Indians,runs,10.0,153.0,20.0,N,NaN,C Shamshuddin,CB Gaffaney

In [6]:
match_ids = matches_2021_2023["id"]

In [7]:
deliveries = deliveries[
    deliveries["match_id"].isin(match_ids)
]

In [8]:
deliveries.shape

(50200, 17)

In [9]:
deliveries.to_csv(
    "../data/processed/deliveries_2021_2023.csv",
    index=False
)